# Window/display constants
window:
  width: 960
  height: 540
  title: Roguelike Survivor
  fps: 60

# World/camera
world:
  width: 2400
  height: 2400
  grid_size: 64

# Gameplay/balance constants
gameplay:
  player:
    move_speed: 180.0
    radius: 14
    color: [60, 200, 255]
    max_health: 100
    regen_per_minute: 0
  enemy:
    base_speed: 80.0
    radius: 12
    color: [240, 70, 70]
    damage: 10
    spawn_per_minute: 60
    spawn_distance_min: 250
  projectile:
    radius: 5
    color: [255, 240, 120]
  pickup:
    radius: 6
    xp_color: [140, 255, 140]

# Spawning/waves
spawning:
  enemy_spawn_interval: 1.0   # seconds
  spawn_increase_every: 30.0  # seconds
  spawn_increase_amount: 0.5  # +50% rate every interval
  offscreen_margin: 80        # pixels beyond the screen to spawn enemies

# Meta progression
meta:
  save_path: save/profile.json
  starting_currency: 0

# Economy — tune post-run currency conversion
economy:
  score_to_currency: 0.1   # currency per 1 score
  kills_to_currency: 0.2   # currency per 1 kill
  time_to_currency: 0.0    # currency per 1 second
